[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive-types = "0.12"
sha2 = "0.10"
hex = "0.4"
thiserror = "2"
journal = { path = "../journal" }
decoder = { path = "../decoder" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "engines"
harness = false

[[bin]]
name = "execution-engine"
path = "src/main.rs"
